### ISSUE TITLE
Soundcloud Downloader

### ISSUE THREAD

**Issue by Fompiw** [Kawaizombi/kawai-scripts#35]
SoundCloud download does not appear anymore making the script useless, appears randomly like when you sign in but then disappears. Please update, Thank You!

**Comment by Kawaizombi** [comment]
Can you please give more details about issue?

1. What browser you use?
2. Do you have any errors in browser console?
3. Way to reproduce(url were issue happens or sequence of actions that cause the problem)

**Comment by Fompiw** [comment]
1.chrome
2. it somehow got fixed thank you!
