### ISSUE TITLE
SoundCloud downloader - Metadata is incorrectly associated with output MP3s

### ISSUE THREAD

**Issue by Fahrenheit** [Kawaizombi/kawai-scripts#40]
When downloading a playlist, some of the songs get the wrong metadata associated with them. The wrong album art, song name, and other details. I was trying to download all my playlists and most my songs are completely mixed up with the wrong associated metadata. Any help would be much appreciated!

**Comment by Kawaizombi** [comment]
Can you give any example of such playlist?

**Comment by Fahrenheit** [comment]
For example, I just downloaded this playlist
Once downloaded the song shown in the photo above was swapped with Death Parade OP. 
You can tell by looking at the song lengths shown in the two select files. The Kiseki By Nirgilis is 4:20 long on Soundcloud and the death parade is 3:26, so the metadata got swapped somehow. This happens to almost every larger playlist I download.

**Comment by Kawaizombi** [comment]
Some updates:

I cannot reproduce it on my machine, but I think I found place that cause issue. Probably this issue appears on slow/unstable internet connection (tracks finises download in other order)

I updated script to v1.5.4 and I hope it will fix this issue

**Comment by Kawaizombi** [comment]
If not feel free to reopen this issue

**Comment by Fahrenheit** [comment]
It seems to be fixed, however it now fails to apply the album art to some songs in playlists.

**Comment by Kawaizombi** [comment]
Give me example please

**Comment by Fahrenheit** [comment]
For example, I downloaded https://soundcloud.com/dj_earworm/sets/dj-earworm-mashups
A few did not have the album art apply. 
![image](https://user-images.githubusercontent.com/33299777/133956891-ea03d6d0-753a-415d-8820-beed65652df0.png)
I confirmed it does not have any album art attached in a tag editor.

**Comment by Kawaizombi** [comment]
Well, in general, these tracks do not have art, what you see in the interface is the avatar of the user who uploaded the track.
